### ISSUE TITLE
user-top-read is an illegal scope?

### ISSUE THREAD

**Issue by James-Quigley** [spotify/web-api#1262]
Issue found on May  30, 2019.

#### Endpoint(s):
* `GET /authorize`

#### Scope(s):
* user-top-read

#### Steps to reproduce:
1. Try to login with an oauth app requesting the 'user-top-read' scope
2. Get a 400 "Illegal scope"

#### Expected behaviour:
Should be prompted with the authorization screen

#### Actual behaviour:
Get a 400 "Illegal scope"

If I use a different scope (e.g. 'user-read-recently-played'), the same code works just fine.

**Comment by summerjets** [comment]
Been banging my head off the wall the past 3 hours with the same error!

**Comment by KeshiaRose** [comment]
Same here.

**Comment by vdesabou** [comment]
Same here. A lot of the users of my Alfred app workflow are impacted.

**Comment by James-Quigley** [comment]
@vdesabou love your Alfred workflow by the way! Bummer that this is impacting it

**Comment by TometoTom** [comment]
I'm getting the same issue. Please help us :)

**Comment by Stevenchaosz** [comment]
Please help us out

**Comment by lumilikha** [comment]
Hey Spotify, please help us get this working better with the Alfred Mac app

**Comment by connorrooney** [comment]
Still getting the same issue as of today

**Comment by NLeRoy917** [comment]
Also ran into this yesterday. Has anyone reached out to spotify?

**Comment by plomdawg** [comment]
Just hit this issue, what's going on?

**Comment by connorrooney** [comment]
Got it working today with the workaround from @nicofilliol
**Keep creating new apps in the dashbaord until it works**
Hopfully spotify will address the issue soon

**Comment by NLeRoy917** [comment]
@connorrooney How many apps did you have to create before it worked?

**Comment by connorrooney** [comment]
@NLeRoy917 I made 5, unsure if it's different for others.

**Comment by gabrielcarneiro97** [comment]
Same issue here...

**Comment by plomdawg** [comment]
Actually I did start noticing this after I deleted then recreated my app...
Thank you @connorrooney I'll try this now

**Comment by sourceleak** [comment]
Same issue here. 
Any fixes?

**Comment by gabrielcarneiro97** [comment]
I created the app like 3 or 4 times and then it started to work, just like magic.

**Comment by ClydSpyd** [comment]
I had this problem and was going crazy. 

As several people have mentioned in this thread, if you keep creating new apps through your Spotify dashboard, it eventually works.

I had to create like 6 or 7 before it worked.

**Comment by J3su2** [comment]
Same issue
Im gald i got it on the first attempt. But without this thread i would still tryin to fix it

**Comment by TechLiam** [comment]
I'm getting this today and ideas on a fix from Spotify been done?

**Comment by NLeRoy917** [comment]
I also got it on the first attempt to remake - I wonder if Spotify fixed something on their end.

**Comment by mklaunzer** [comment]
Thanks for your hints! This has been caused by a configuration issue on some our hosts and caused some newly created client ids missing the user-top-read scope. This has been fixed now - when creating a new client id, the scope should now always be available.
We are working on also adding it to the client ids which did not receive it during creation. This will take some more time, so if you need this to work urgently, please create a new client id for now.

**Comment by dolsem** [comment]
I've just created a new client id and it still has the same issue.

**Comment by denizdemirci1** [comment]
I've faced this issue yesterday and have been recreating my app on Spotify Developer Console since then, probably more than 15 times. Didn't solve my problem.

When I add "user-top-read" into the scopes, I get following error while requesting the token:
"AUTHENTICATION_SERVICE_UNKNOWN_ERROR"
