### ISSUE TITLE
502 - 'Failed to follow artists' - for a specific artist

### ISSUE THREAD

**Issue by astalwick** [spotify/web-api#166]
This appears to be an issue with a particular artist account.

When I follow the artist with id 1K80Wcuuo13i28cVd68mxm via the web api, I get 502 Bad Gateway, with the response body: { "error": { "status": 502, "message": "Failed to follow artists"}}.

For all other artists, the request works correctly.

Endpoint: 
- https://api.spotify.com/v1/me/following

Steps to Reproduce: 
- Use the API Console, https://developer.spotify.com/web-api/console/put-following/
- Use Type: artist and ID: 1K80Wcuuo13i28cVd68mxm 

Expected: 
- Follow the artist

Actual: 
- 502 Bad Gateway - - -  { "error": { "status": 502, "message": "Failed to follow artists"}}

**Comment by thelinmichael** [comment]
Thanks for the report @astalwick, can confirm that the API is consistently returning server error responses and that the artist never gets followed. We'll investigate further.

**Comment by biohzrdmx** [comment]
Hey guys, we're having the same error, it's failing for this artist too: 1bfl0AU8SqmLkElptOprhC
Exactly the same error.

Regards.

**Comment by thelinmichael** [comment]
Closing this ticket as this bug has been fixed. 🎉 🎈

**Comment by michaelfoster9** [comment]
@thelinmichael I'm using a .NET SDK to talk to the Spotify server.  I see a very similar error still. Instead of getting a Failed To Follow artists error, I am getting the following
"{\n  \"error\": {\n    \"status\": 502,\n    \"message\": \"Failed to get followed artists\"\n  }\n}"

I am trying to get a list of all of the artists that a user is following using the paging apis.  In this particular case, the user is following about 2000 artists and it's failing around the 200th artist.  I dont have a great way of knowing exactly what artist it is failing on.

Does this sound like the same problem to you or a separate error?

thanks,
michael

**Comment by richardgazdik** [comment]
@thelinmichael Same thing here. This artist id generates the error in the request: 0p4HbDx1JTF3QLaBznAOrU

**Comment by michaelfoster9** [comment]
I belive that this issue should be reopened due to multiple people still seeing problems.  This ticket below talks about a similar problem.  My apps customers are complaing because for many of the, the features that used to work no longer work because of this defect.  Being able to retreive the list of artists that a user follows is an integral part of the sdk and when that stops working, it makes it really hard to support our integration with Spotify.

https://github.com/spotify/web-api/issues/275

**Comment by thelinmichael** [comment]
@michaelfoster9 and @richardgazdik, are you having issues with following the artist, or retrieving the list of followed artists? Let's separate the issues so that we talk about the [Follow Artist endpoint](https://developer.spotify.com/web-api/follow-artists-users/) here, and the [Get User's Followed Artists](https://developer.spotify.com/web-api/get-followed-artists/) in #275. From your last posts it's not apparent if there are still issues with this particular ticket. Thanks!

**Comment by michaelfoster9** [comment]
@thelinmichael Sorry for the confusion.  In my case, I am talking about retrieving the list of followed artists.  My comment in this post was only to indicate that the errors seemed similar and related and when i saw that @richardgazdik appeared to have the same problem...it made me think that there was still and artist that can "go bad" and when that happens, it prevents you from following that artist OR retrieving a list of followed artists when that artist is in the list.

thank you for your time on this issue.  It is very important to me and all help is much appreciated.

**Comment by asmitter** [comment]
Closing this as there were no new reports for the "follow" action, and the outstanding reports from @michaelfoster9 and @richardgazdik can be tracked here: https://github.com/spotify/web-api/issues/275
