### ISSUE TITLE
Incorrect charset specified in response header for /audio-features. (UTF8 vs utf-8)

### ISSUE THREAD

**Issue by VirUZI** [spotify/web-api#291]
The audio feature endpoints return an incorrect charset. This prevent the standard .net HttpClient from reading the response unless a correct charset is forced. 

Example:
GET https://api.spotify.com/v1/audio-features?ids=34qzPL32IXcaU3ALyMtHtV
Returns the header "Content-Type: application/json; charset=UTF8"

The expected charset is "utf-8" in the same way as all other web api endpoints.

**Comment by jooon** [comment]
I noticed the same problems for:
https://api.spotify.com/v1/me/top/{type}
https://api.spotify.com/v1/recommendations
https://api.spotify.com/v1/recommendations/available-genre-seeds

**Comment by jooon** [comment]
Ok. The root cause is already fixed

https://github.com/spotify/apollo/pull/147

but these services have not been updated internally.

**Comment by thelinmichael** [comment]
Thanks for reporting @VirUZI, and for digging @jooon! We're updating the services gradually, so we'll get this issue sorted soon. We'll update this ticket when it's done.

**Comment by fjalarsson** [comment]
@thelinmichael Hi Michael, any update on when this is going to get fixed?

**Comment by thelinmichael** [comment]
We've just deployed a patch to fix this issue. 🔧 🔨 

Thanks again for letting us know @VirUZI, much appreciated. 

Ping @fjalarsson, @jooon

**Comment by daniel-centore** [comment]
This problem still exists for at least https://api.spotify.com/v1/recommendations
