### ISSUE TITLE
[KNOWN ISSUE] /v1/me/player/currently-playing returns out-of-date information

### ISSUE THREAD

**Issue by asmitter** [spotify/web-api#499]
We are aware of an issue affecting a minority of users where the Web API endpoints to retrieve the user's currently playing track will - under certain conditions -  not report up-to-date information.

**If you have this issue, please report your Spotify username in the comments below or via DM to the [Spotify Platform twitter account](https://twitter.com/SpotifyPlatform).**

We are working on a fix, but until then we are able to resolve it on a user-by-user basis.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`
* `GET /v1/me/player`

#### Scope(s):
* `user-read-currently-playing` or `user-read-playback-state` (depending on endpoint)

#### Steps to reproduce:
1. Start playing a track in the Spotify client.
2. Make an authenticated call with the correct scopes to one of the above endpoints (for example, using the [API Console](https://developer.spotify.com/web-api/console/get-users-currently-playing-track/))
3. Check the response to see if it matches the song currently playing in the Spotify client.

#### Expected behaviour:
The response contains accurate information about what is currently playing in the Spotify client.

#### Actual behaviour:
The response contains out-of-date information.

**Comment by dreszczyk** [comment]
I'm having this issue, my spotify ID is `21uhpnr3i2xtha4gcu4jhbszq` but with `v1/me/player` endpoint.

**Comment by pauljnoble** [comment]
Thanks @asmitter my user id is 1231269878

**Comment by asmitter** [comment]
Fixed for @pauljnoble and @dreszczyk

**Comment by kvanzuijlen** [comment]
My user id is `1131582039`. Thanks in advance.

**Comment by asmitter** [comment]
Fixed for @kvanzuijlen

**Comment by tobyonono** [comment]
It's for both of my accounts 'toby onono' and 'ludotestaccount'. Thanks.

**Comment by dreszczyk** [comment]
Well, it's not working good - my desktop player is locked (music is playing, but the timeline and controls are not updating).

**Comment by chan135** [comment]
Can you fix it for userids = 1237666383, 1235536440

**Comment by asmitter** [comment]
Fixed for both @chan135 accounts and @tobyonono accounts.

@dreszczyk this doesn't sound like a Web API issue. If you still have problems with your desktop player after the usual restart etc, head over to https://support.spotify.com or reach out to [@spotifycares on twitter](https://twitter.com/SpotifyCares).

**Comment by jpiepkow** [comment]
userid: 1212971463

Thanks!

**Comment by jpiepkow** [comment]
@asmitter could you let me know when you get to my userid. I also messaged on the spotify platform twitter about a week ago. I currently have to open the mobil application in order to get my current songs to pick up. Thanks!

**Comment by davidvorona** [comment]
Having issues with out-of-date information with the 'currently-playing' endpoint.

userid: 'vijuhas'

Thanks!

**Comment by asmitter** [comment]
Fixed for @davidvorona and @jpiepkow

**Comment by jpiepkow** [comment]
Just a update @asmitter but the fix you put in place for user did not work for my account apparently or you may have another issue. This morning I tested getting current song in both osx and windows application and it constantly displayed an older song I was listening to until I open the android application..then it started tracking correctly. Once you have more information on this issue can you please reach out. Thanks!

**Comment by jpiepkow** [comment]
Looks to have cleared up for the time but in my first hour of testing I was still having issues. Thanks though!

**Comment by cassiohub** [comment]
Hello

I'm facing the same issue. If can you apply the fix to my user would be great. my user is 12129631691 (facebook linked account). Thanks

**Comment by asmitter** [comment]
@cassiohub - fixed.

**Comment by TLmaK0** [comment]
Hi @asmitter, same problem with user 1184742927

**Comment by asmitter** [comment]
@TLmaK0 fixed.

**Comment by andersonshatch** [comment]
I'm not sure if I'm experiencing the same thing -- with the `GET /v1/me/player` endpoint, the device (specifically its `volume_percent`) is not updating when changed, it stays incorrect until the song changes; `GET /v1/me/player/devices` does return the correct updated value for the devices volume though.

**Comment by ohcrapitsandrew** [comment]
Hello @asmitter same problem... user is andrew_t29

Thanks in advance!!

**Comment by jonosorio** [comment]
Hey @asmitter , having the same issue here, user id is jjob95

Thank you so much for your help!

**Comment by asmitter** [comment]
Fixed for @ohcrapitsandrew and @jonosorio

**Comment by asmitter** [comment]
We have now deployed a fix for all users.
If you still see this issue, please open a new ticket with your Spotify username so we can investigate.

**Comment by TLmaK0** [comment]
I have noticed that after close the player while it's playing, the API still showing that the player is running.

**Comment by asmitter** [comment]
@TLmaK0 Sounds like you're experiencing #533

**Comment by VictorXLR** [comment]
Hi, 

I am trying to implement the now playing Api in a python script using spotipy. but i keep getting an invalid username error.

This is my code
```py
import spotipy, authData, os, pprint
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy.util as util

client_credentials_manager = SpotifyClientCredentials()
token = client_credentials_manager.get_access_token()
spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager, auth=client_credentials_manager.get_access_token())

me = 'son_of_wanye'  #spotify_ id . 
def Nowplaying():
	url ='https://api.spotify.com/v1/me/player/currently-playing'
	now_playing = spotify._get('me/player/currently-playing')
	return nowPlaying

pprint.pprint(Nowplaying())
```
this gave me an invalid username error

did this then
```py
import spotipy, authData, os, pprint
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy.util as util

client_credentials_manager = SpotifyClientCredentials()
token = client_credentials_manager.get_access_token()
spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager, auth=client_credentials_manager.get_access_token())

me = 'son_of_wanye'
def Nowplaying():
	url ='https://api.spotify.com/v1/me/player/currently-playing'
	now_playing = spotify._get('{}/player/currently-playing'.format(me))
	return nowPlaying

pprint.pprint(Nowplaying())
```
gave me Error. I dont understand what the problem is. It plainly gave me an Error

**Comment by pigi5** [comment]
Also getting way out of date information. My user is pigi5

**Comment by tance77** [comment]
I'm getting out of date information. User: 121058598

**Comment by thepassle** [comment]
This still seems to be a problem. Not getting the currently-playing song. Username: lord_brad
@asmitter

**Comment by rickmzp** [comment]
User: digx

**Comment by robinwyss** [comment]
I am having this issue, user: 202a

**Comment by artechventure** [comment]
I'm having this issue too, still not fixed? :(

**Comment by artechventure** [comment]
I getting out of date information ( song played about 30min ago )
