### ISSUE TITLE
Search by upc is not working

### ISSUE THREAD

**Issue by dudil** [spotify/web-api#621]
Issue found on 23/07/2017

#### Endpoint(s):
* `https://api.spotify.com/v1/search`

#### Scope(s):
* Full autherization (all fields are marked as approved by user)

#### Steps to reproduce:
1. Open the API console
2. search by KW upc with a valid ups number
3. get empty list
Bonus - same is failed to work also for the app itself

#### Expected behaviour:
According to the updated documentation there is a support for search by UPC code.
https://developer.spotify.com/web-api/search-item/

Bonus: Also this should work for the application itself but failed
https://developer.spotify.com/web-api/search-item/

#### Actual behaviour:
empty list returns from server.
(even for example upc from documentation - 00602537817016 or for known to work upc 028946376126) which works perfectly with apple music search API https://itunes.apple.com/lookup?upc=028946376126)

**Comment by arirawr** [comment]
Hi @dudil - the example in the documentation works for me. Try it out in the console here: [https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A00602537817016&type=album](https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A00602537817016&type=album)

For the other example you provide, adding two zeros to the beginning of the code you provide gives the expected behaviour. I've asked the appropriate team about this and will get back to you if I get more info. You can try the call with your provided UPC here: [https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A00602537817016&type=album](https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A00602537817016&type=album)

**Comment by dudil** [comment]
Thanks @arirawr 
To be honest the example still failed to work but using the API with the 00 prefix did the work and it is working now (tried it with my own UPC 028946376126 -> 00028946376126).
I will be happy to know if this is required by the API or an issue that will be resolved (before implementing any workaround for that)

**Comment by bih** [comment]
Hi @dudil,

The expected value, as from the example, should begin with `00`. You should write your code to adhere to that as follows. As this is resolved, I'll be closing this - but reach out if you have any other questions - we would love to help! 👍

**Comment by Agnostic** [comment]
Hi, I still have the same issue even if I add `00` to the upc.

This is the UPC code I am trying to find:
760377763327

Tried with:
`q=upc%3A760377763327&type=album`

and
`q=upc%3A00760377763327&type=album`

https://open.spotify.com/album/2jwZ1QoNuIXfuHT0HMZhVL?si=I7LdmDIfTOa8AvFvBq8q9A

**Comment by Agnostic** [comment]
Any idea @bih ?
