### ISSUE TITLE
"INVALID_CLIENT: Invalid redirect URI" on https://beta.developer.spotify.com/console

### ISSUE THREAD

**Issue by jasonhenderson** [spotify/web-api#857]
Issue found on February 19th 2015.

#### Endpoint(s):
* `ALL`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Open the `get-users-profile` endpoint
3. Click Refresh Token with any scope

#### Expected behaviour:
Token refreshes.

#### Actual behaviour:
"INVALID_CLIENT: Invalid redirect" returned

**Comment by lievcin** [comment]
Experiencing the same behavior

**Comment by hughrawlinson** [comment]
Thanks for letting us know! We pushed a bad build to production. Working on a fix now.

**Comment by hughrawlinson** [comment]
This is fixed now :)

**Comment by culinko** [comment]
Hi. I'm still getting "INVALID_CLIENT: Invalid redirect" after clicking on the "Request Token" button. After clearing my cookies, I was able to get two additional pages, the first one was a selection between logging in and signing up to Spotify, the second one was a selection between Facebook login and Spotify login. After clicking on the Facebook login, I'm still getting "INVALID_CLIENT: Invalid redirect".

**Comment by hughrawlinson** [comment]
Oh, that's odd. I'll look into it now :)

**Comment by culinko** [comment]
Thank you very much! It seems to be working as of now :)

**Comment by arirawr** [comment]
Great to hear! Feel free to reopen if you see any further issues.
