### ISSUE TITLE
Audio Features not working for certain Spotify tracks

### ISSUE THREAD

**Issue by DijonLee** [spotify/web-api#923]
Issue found on June 23 2018

After playing around with the get audio features it looks like the audio features are missing for new tracks. The tracks are recent on spotify so I think it might just be that audio features are not available (yet). Is getting audio features such as valence and the like an automatic process or is it manual?

#### Endpoint(s):
* `curl -X "GET" "https://api.spotify.com/v1/audio-features?ids=1vi9adPJiD4d22ybGp25hy%2C1vi9adPJiD4d22ybGp25hy%2C5JoUwqXt9IPLbiJ6pXwarL%2C6w9lmWBgqzPQHNQo5KaORN%2C5FYu8uBB6E11mepU601601" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQDJaNpzk12RMpThPr9D4VY8qLXdCsvUEuMqR0wUH0agxpWNOQP8_yacPctHuo6Y4jrVNJwd2IrLfPyduUsjMrkgTiG4Pz7yS17Fz08S8uXAcP37tdiGaWpRwuxkTB23qZMm-JzVANOTfeUaUavpj3TCy3ZSrITMDgnihBnVmyFiNa68eiF_o2u9RGIzq-XAFIQVwxTbXeX8Eoxs7G3Q_e9imHJweTaB-b9EOLNiZXEVJdi2_v8YQxVNpN_t_XzehDx_A8pU2fGwWb3fEA"`

#### Scope(s):
user-read-private
user-read-birthdate
user-read-email
playlist-read-private
user-library-read
user-library-modify
user-top-read
playlist-read-collaborative
playlist-modify-public
playlist-modify-private
user-follow-read
user-follow-modify
user-read-playback-state
user-read-currently-playing
user-modify-playback-state
user-read-recently-played

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-features` endpoint with the following track ID's:

1vi9adPJiD4d22ybGp25hy,1vi9adPJiD4d22ybGp25hy,5JoUwqXt9IPLbiJ6pXwarL,6w9lmWBgqzPQHNQo5KaORN,5FYu8uBB6E11mepU601601

#### Expected behaviour:
` {
      "danceability": 0.585,
      "energy": 0.842,
      "key": 9,
      "loudness": -5.883,
      "mode": 0,
      "speechiness": 0.0556,
      "acousticness": 0.00242,
      "instrumentalness": 0.00686,
      "liveness": 0.0866,
      "valence": 0.428,
      "tempo": 118.211,
      "type": "audio_features",
      "id": "2takcwOaAZWiXQijPHIx7B",
      "uri": "spotify:track:2takcwOaAZWiXQijPHIx7B",
      "track_href": "https://api.spotify.com/v1/tracks/2takcwOaAZWiXQijPHIx7B",
      "analysis_url": "https://api.spotify.com/v1/audio-analysis/2takcwOaAZWiXQijPHIx7B",
      "duration_ms": 237040,
      "time_signature": 4
    }
  ]
}`.

#### Actual behaviour:
`{
  "audio_features": [
    null,
    null,
    null,
    null,
    null
  ]
}`

**Comment by bih** [comment]
Hi @0xNF!

Thanks for reporting this bug! We've identified the bug you mentioned and are looking into resolving it as we speak. We'll post updates here 👍

**Comment by bih** [comment]
We can now confirm this issue has been resolved. The track IDs you posted all now seem to be working. I'll close this issue as it is fixed, but feel free to re-open if you continue to have issues!

Thanks @0xNF!

**Comment by 0xNF** [comment]
As much as I like getting credit for this, @DijonLee posted the original report, so any credit should really be directed his way.

**Comment by NaturalFigurehead** [comment]
@bih 

I don't think this issue is resolved. I'm continuing to see many newer tracks without audio features. Even very popular tracks. As of right now these 2 ids return no audio features for tracks that have been released almost 2 weeks ago and are on the billboard top 100: `7b8YOVV5quZcSKEijDgyWB` `1ZEm9cJC05rawV2tptNfTS`.

**Comment by tomjaimz** [comment]
I agreed with @NaturalFigurehead that this issue is still not resolved.  I have opened a new one - https://github.com/spotify/web-api/issues/929 - in an attempt to address it.

**Comment by bih** [comment]
Hey @DijonLee,

We're investigating this issue again. Apologies, we thought this was resolved. We'll post updates here :)

**Comment by tomjaimz** [comment]
I'll repeat my submission of my own experience with this bug (#929) here.

I have a playlist that is automatically updated daily, and uses audio features for sorting.  It's been working fine for over a year, however since June 18th it has been failing due to a significant increase in the volume of tracks that lack an audio feature profile.

I see that 923 was opened recently, and a recent comment indicates at least one other person encountering this problem.

I would say I have added over 2,000 tracks to my playlist in the last year or so, and of those perhaps only 2 or 3 failed to get audio feature objects.  Since June 18th, 21 new tracks have failed to return audio feature objects.

The solution to 923 seems to indicate that audio feature objects were created for the tracks that the reporter had encountered, but it seems to be the issue is systemic.

Issue found on June 18th, 2018.

My description below highlights the 21 tracks released since June 18th that do not have audio-feature objects:

#### Endpoint(s):
* `GET /v1/audio-features?ids=4VPMoAVfD2UCacipd11PJw%2C3ne6hRkl1MgLf0WwRhZXU3%2C7dRJLvM0RMByeJNnbthm6E%2C4xowQvAlaQlAfXHYtcBxe2%2C2prRXBrhnd3BSIP63Ld59L%2C2IOwkPAkDDGvkLzlnUdcQ2%2C2kGqcecDUhi7e3wvm5cUjY%2C14CX3nEihqZK9lR9XrcNYJ%2C0kxojsWbN5U4krbk8yYWpd%2C4jkYCDN1arnPQ5HcWChhKG%2C0T8C8LTnhPcpRwTiUWGzBQ%2C7t0MNDhyv0ggclROXkmJuO%2C1iRlHOS7o2YYZtUlUZhHtl%2C3IBOf42ijoA4EzB5CIcfog%2C5BOHxzYSDYY5jHoqDY7YWT%2C4vBgr4V2GOuBi896Thvgsg%2C3sxYw4AzSqS193y7B31n2t%2C2iGvIF4GcWHop2XOoYkdpd%2C1uZwnxyUTiuVl7U8I2f5E1%2C5sn7f3na9nvZmgfXdi33Ts%2C07wtxHqUa3UHKBwM2a48hf`

#### Scope(s):
* None (but OAuth requred)

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-features` endpoint with `ids` `4VPMoAVfD2UCacipd11PJw,3ne6hRkl1MgLf0WwRhZXU3,7dRJLvM0RMByeJNnbthm6E,4xowQvAlaQlAfXHYtcBxe2,2prRXBrhnd3BSIP63Ld59L,2IOwkPAkDDGvkLzlnUdcQ2,2kGqcecDUhi7e3wvm5cUjY,14CX3nEihqZK9lR9XrcNYJ,0kxojsWbN5U4krbk8yYWpd,4jkYCDN1arnPQ5HcWChhKG,0T8C8LTnhPcpRwTiUWGzBQ,7t0MNDhyv0ggclROXkmJuO,1iRlHOS7o2YYZtUlUZhHtl,3IBOf42ijoA4EzB5CIcfog,5BOHxzYSDYY5jHoqDY7YWT,4vBgr4V2GOuBi896Thvgsg,3sxYw4AzSqS193y7B31n2t,2iGvIF4GcWHop2XOoYkdpd,1uZwnxyUTiuVl7U8I2f5E1,5sn7f3na9nvZmgfXdi33Ts,07wtxHqUa3UHKBwM2a48hf`

#### Expected behaviour:
Array of audio feature objects t as described on `https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/`.

#### Actual behaviour:
Array of nulls.

**Comment by 0xNF** [comment]
I'd like to add another song that doesn't have audio features:

Spotify Id: 03X1fnJyeBsxt1qAnmcXtq
A PLEASANT MEAL by Suran

Like the behavior described above, this returns a null entry when used with Get Several Audio Features:

```bash
curl -X "GET" "https://api.spotify.com/v1/audio-features?ids=03X1fnJyeBsxt1qAnmcXtq" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer [token]"
```
Returns:
```json
{
  "audio_features": [
    null
  ]
}
```

Similarly, when using the single audio features endpoint, a'la:
```bash
curl -X "GET" "https://api.spotify.com/v1/audio-features/03X1fnJyeBsxt1qAnmcXtq" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer [token]"
```
returns:
```json
{
  "error": {
    "status": 404,
    "message": "analysis not found"
  }
}
```

**Comment by gustavoaca1997** [comment]
I don't know if it is related but when I copy the song URI from certain playlist, the endpoint won't return the features.

For example "_Con Altura_" by Rosalia:
`spotify:track:2qG5sZ7Si6sdK74qLxedYM` <- song URI copied from a playlist of mine

`spotify:track:2qG5sZ7Si6sdK74qLxedYM?context=spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DX10zKzsJ2jva` <- song URI copied from _¡Viva Latino!_ playlist. This one won't return the features.

**Comment by alexfaren** [comment]
was this ever solved. starting a project using this api but it is worthless if i can't pull the features for a large variety of tracks

**Comment by DijonLee** [comment]
It wasn't solved but it looks like the issue isn't "widespread". I wish they would explain why this happens or offer an alternative fix

**Comment by alexfaren** [comment]
do you have any further information on how frequently this happened to you? 1 in 1000? 1 in 10000?

I have seen similar projects running off of 130K songs and the person did not mention this issue.

**Comment by DijonLee** [comment]
I'd say about 1 in 1000

**Comment by holmstromjesper** [comment]
> was this ever solved. starting a project using this api but it is worthless if i can't pull the features for a large variety of tracks

I might have some enlightenment on the issue. I got some problems with their API when working with "large" volumes, to early to say if its an error on my end (resulting in rate limiting) or if I'm hitting the rate limit in the proper way. However, I fetch 4000ish track objects, from their IDs I fetch their audio feature objects and I hit the rate limit. Do you have any links to the 130k projects?

**Comment by alexfaren** [comment]
https://www.kaggle.com/tomigelo/spotify-audio-features @holmstromjesper

**Comment by isaurabh19** [comment]
Has this issue been solved? I am fetching a list of ids by searching for them using search endpoint and for the first 500 resulting ids, no audio features are available
